title: The Blockchap
blog-logo: logo/blockchap.svg # blog logo
description: > # this means to ignore newlines until the next field
  The Blockchap writes about Blockchain technology.
  You'll find articles related to Blockchain, Bitcoin, Ethereum, Hyperledger, cryptocurrencies in general, and of various levels of complexity, starting from the very basics to ICO reviews.
  All that explained in a friendly way to help everyone understands the ever-expanding Blockchain universe.
keywords: blockchain,blockchap,Federico,Madotto,blog,bitcoin,ethereum,hyperledger,eris,monax,crytocurrency,crypto,cryptocurrencies,ICO,review,analysis,consulting,cryptography,satoshi,nakamoto
permalink: ':year/:month/:day/:slug/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.federicomadotto.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Federico Madotto # add your name
author-image: squarepic.jpg # add your photo
author-image-icon: squarepic60x60.jpg # add your photo
about-author: Blockchain enthusiast and obsessive learner.<br />I enjoy reading about cool and challenging topics and write about them in simple terms. # add description
twitter: federicomadotto # add your Twitter handle
facebook: # add your Facebook handle
github: fmadotto # add your Github handle
linkedin: # add your Linkedin handle
email: federico (dot) madotto (at) gmail.com # add your Email address

# Article settings
default-cover-image: default-cover.jpg

# Disqus
disqus-identifier: federicomadotto # add your disqus identifier

# Tracker
analytics: UA-107542911-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - "package.json"
  - "node_modules"
  - "gulpfile.js"
  - "Gemfile*"
