title: Free the blocks!
blog-logo: squarepic.jpg # blog logo
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':year/:month/:day/:slug/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://fmadotto.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Federico Madotto # add your name
author-image: squarepic.jpg # add your photo
about-author: Blockchain enthusiast and obsessive learner.<br />I like to read about somewhat challenging notions and reword them in simpler terms. # add description
twitter: federicomadotto # add your Twitter handle
facebook: # add your Facebook handle
github: fmadotto # add your Github handle
linkedin: # add your Linkedin handle
email: federico (dot) madotto (at) gmail.com # add your Email address

# Article settings
default-cover-image: default-cover.jpg

# Disqus
diqcus-identifier: federicomadotto # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
